# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/bridge_sidecar.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/bridge_sidecar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/bridge_sidecar.proto\x12\x0fpoolside.bridge\"3\n\tRunDetail\x12\x12\n\nagent_name\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"\xa0\x02\n\x0c\x43ontinueFrom\x12\x37\n\x13previous_run_detail\x18\x01 \x01(\x0b\x32\x1a.poolside.bridge.RunDetail\x12J\n\x0c\x63ontinuation\x18\x02 \x01(\x0b\x32\x32.poolside.bridge.ContinueFrom.NoCompactionStrategyH\x00\x12\x46\n\ncompaction\x18\x03 \x01(\x0b\x32\x30.poolside.bridge.ContinueFrom.CompactionStrategyH\x00\x1a\x16\n\x14NoCompactionStrategy\x1a\x14\n\x12\x43ompactionStrategyB\x15\n\x13\x63ompaction_strategy\"\x80\x01\n\x11StartAgentRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nagent_name\x18\x02 \x01(\t\x12\x11\n\tdirectory\x18\x03 \x01(\t\x12\x34\n\rcontinue_from\x18\x04 \x01(\x0b\x32\x1d.poolside.bridge.ContinueFrom\"Y\n\x12StartAgentResponse\x12.\n\nrun_detail\x18\x01 \x01(\x0b\x32\x1a.poolside.bridge.RunDetail\x12\x13\n\x0b\x65xit_result\x18\x03 \x01(\t2m\n\x14\x42ridgeSidecarService\x12U\n\nStartAgent\x12\".poolside.bridge.StartAgentRequest\x1a#.poolside.bridge.StartAgentResponseB.Z,github.com/poolsideai/forge/pkg/bridge/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.bridge_sidecar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/poolsideai/forge/pkg/bridge/proto'
  _globals['_RUNDETAIL']._serialized_start=47
  _globals['_RUNDETAIL']._serialized_end=98
  _globals['_CONTINUEFROM']._serialized_start=101
  _globals['_CONTINUEFROM']._serialized_end=389
  _globals['_CONTINUEFROM_NOCOMPACTIONSTRATEGY']._serialized_start=322
  _globals['_CONTINUEFROM_NOCOMPACTIONSTRATEGY']._serialized_end=344
  _globals['_CONTINUEFROM_COMPACTIONSTRATEGY']._serialized_start=346
  _globals['_CONTINUEFROM_COMPACTIONSTRATEGY']._serialized_end=366
  _globals['_STARTAGENTREQUEST']._serialized_start=392
  _globals['_STARTAGENTREQUEST']._serialized_end=520
  _globals['_STARTAGENTRESPONSE']._serialized_start=522
  _globals['_STARTAGENTRESPONSE']._serialized_end=611
  _globals['_BRIDGESIDECARSERVICE']._serialized_start=613
  _globals['_BRIDGESIDECARSERVICE']._serialized_end=722
# @@protoc_insertion_point(module_scope)
