# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import bridge_pb2 as proto_dot_bridge__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BridgeServiceStub(object):
    """Bridge service for managing agent operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartAgent = channel.unary_unary(
                '/poolside.bridge.BridgeService/StartAgent',
                request_serializer=proto_dot_bridge__pb2.StartAgentRequest.SerializeToString,
                response_deserializer=proto_dot_bridge__pb2.StartAgentResponse.FromString,
                _registered_method=True)


class BridgeServiceServicer(object):
    """Bridge service for managing agent operations
    """

    def StartAgent(self, request, context):
        """Start an agent with a given prompt
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAgent,
                    request_deserializer=proto_dot_bridge__pb2.StartAgentRequest.FromString,
                    response_serializer=proto_dot_bridge__pb2.StartAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'poolside.bridge.BridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('poolside.bridge.BridgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BridgeService(object):
    """Bridge service for managing agent operations
    """

    @staticmethod
    def StartAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/poolside.bridge.BridgeService/StartAgent',
            proto_dot_bridge__pb2.StartAgentRequest.SerializeToString,
            proto_dot_bridge__pb2.StartAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
