# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/bridge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/bridge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/bridge.proto\x12\x0fpoolside.bridge\"1\n\tRunDetail\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"\xa0\x02\n\x0c\x43ontinueFrom\x12\x37\n\x13previous_run_detail\x18\x01 \x01(\x0b\x32\x1a.poolside.bridge.RunDetail\x12J\n\x0c\x63ontinuation\x18\x02 \x01(\x0b\x32\x32.poolside.bridge.ContinueFrom.NoCompactionStrategyH\x00\x12\x46\n\ncompaction\x18\x03 \x01(\x0b\x32\x30.poolside.bridge.ContinueFrom.CompactionStrategyH\x00\x1a\x16\n\x14NoCompactionStrategy\x1a\x14\n\x12\x43ompactionStrategyB\x15\n\x13\x63ompaction_strategy\"5\n\x11StartAgentRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\"Y\n\x12StartAgentResponse\x12.\n\nrun_detail\x18\x01 \x01(\x0b\x32\x1a.poolside.bridge.RunDetail\x12\x13\n\x0b\x65xit_result\x18\x03 \x01(\t2f\n\rBridgeService\x12U\n\nStartAgent\x12\".poolside.bridge.StartAgentRequest\x1a#.poolside.bridge.StartAgentResponseB.Z,github.com/poolsideai/forge/pkg/bridge/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.bridge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/poolsideai/forge/pkg/bridge/proto'
  _globals['_RUNDETAIL']._serialized_start=39
  _globals['_RUNDETAIL']._serialized_end=88
  _globals['_CONTINUEFROM']._serialized_start=91
  _globals['_CONTINUEFROM']._serialized_end=379
  _globals['_CONTINUEFROM_NOCOMPACTIONSTRATEGY']._serialized_start=312
  _globals['_CONTINUEFROM_NOCOMPACTIONSTRATEGY']._serialized_end=334
  _globals['_CONTINUEFROM_COMPACTIONSTRATEGY']._serialized_start=336
  _globals['_CONTINUEFROM_COMPACTIONSTRATEGY']._serialized_end=356
  _globals['_STARTAGENTREQUEST']._serialized_start=381
  _globals['_STARTAGENTREQUEST']._serialized_end=434
  _globals['_STARTAGENTRESPONSE']._serialized_start=436
  _globals['_STARTAGENTRESPONSE']._serialized_end=525
  _globals['_BRIDGESERVICE']._serialized_start=527
  _globals['_BRIDGESERVICE']._serialized_end=629
# @@protoc_insertion_point(module_scope)
